spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xyz
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update